# Generated by Django 5.2.2 on 2025-06-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0002_chatgroup_user_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='user_online',
            new_name='users_online',
        ),
    ]
